channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=23.0.1
- pip:
  - mlflow==2.3
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - ipython==8.12.0
  - numpy==1.24.3
  - packaging==21.3
  - pytorch-lightning==2.0.2
  - pyyaml==6.0
  - requests==2.31.0
  - torch==2.0.1
  - torchvision==0.15.2
name: mlflow-env