channels:
- conda-forge
dependencies:
- python=3.9.17
- pip<=23.2.1
- pip:
  - mlflow==2.5.0
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - ipython==8.13.1
  - numpy==1.23.5
  - packaging==23.0
  - pytorch-lightning==2.0.2
  - pyyaml==6.0
  - requests==2.29.0
  - torch==2.0.1
  - torchvision==0.15.2
name: mlflow-env